### ISSUE TITLE
crash when registering a user

### ISSUE THREAD

**Issue by argrath** [puckipedia/Kroeg#16]
I'm trying to run Kroeg on vagrant:

 * install dotnet-sdk-2.0.2
 * install postgresql-9.6
   * create database named 'activitypub'
   * set the password of user 'postgres' to 'postgres'
 * git clone
 * dotnet run
 * access /auth/register
 * enter some data and submit

causes `An unhandled exception occurred while processing the request.` with [this log](https://github.com/puckipedia/Kroeg/files/1552145/errorlog.txt).

Is there any extra work to run?

```
$ dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by puckipedia** [comment]
There shouldn't be. I wasn't able to reproduce this, so I just pushed a commit that should help testing this.

Could you run it again and if it crashes again attach the new logs?

**Comment by argrath** [comment]
My apologies for bothering you.
I'm trying to run on VM with vagrant, so I need to modify BaseUri on `appsettings.json` to the VM's one.
After modifing, it worked fine.

**Comment by puckipedia** [comment]
No issue! I tried replicating this but I couldnt, even when the BaseUri didn't correspond to the host it ran on... That's why I wondered why it didn't work
