### ISSUE TITLE
HTTP signatures?

### ISSUE THREAD

**Issue by puckipedia** [puckipedia/Kroeg#6]
Format: https://github.com/w3c/activitypub/issues/203#issuecomment-297553229

`publicKey` be a pem format. keyId would be the ID of the key above?

could be together with JWT and Kroeg could support both. need to rewrite JsonWebToken table

Interop with Mastodon?

**Comment by Gargron** [comment]
For reference: https://github.com/tootsuite/mastodon/pull/4146
